properties/urls.py
from django.conf.urls import url
from . import views

app_name = 'property'

urlpatterns = [


url(r'^list/$',views.Properties_List,name = "list"),

url(r'^search/$',views.search,name = "search"),

url(r'^category/(?P<pk>[-\w]+)/$',views.Properties_Category_List,name = "category"),

url(r'^detail/(?P<pk>[-\w]+)/$',views.Property_detail.as_view(),name = "detail"),

]

realestate/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from django.conf.urls.static import static
from . import settings 
from profile_details.views import SignUp


urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^accounts/', include('django.contrib.auth.urls')), 
	url(r'^profile/',include('profile_details.urls')),
	url(r'^property/',include('properties.urls')),
	url(r'^$',views.Home,name = 'index'),
	url(r'^about/$',views.About,name = 'about'),
	url(r'^success/$',views.success,name = 'success'),

	
] 
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

properties/models.py
from django.db import models


# Create your models here.

from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

class Category(models.Model):
	title = models.CharField(max_length=20)

	def __str__(self):
		return self.title


class Property(models.Model):
	title = models.CharField(max_length = 210,default = 'None')

	STATUS_CHOICES = (
	('RENT','Rent'),
	('SALE','Sale'),
		)

	status = models.CharField(max_length = 210,choices = STATUS_CHOICES,default = 'Rent')

	price = models.IntegerField()
	
	area = models.CharField(max_length = 210,default = 'None')

	ROOM_CHOICES = (
	('1','1'),
	('2','2'),
	('3','3'),
	('4','4'),
	('MORE','More'),
		)

	rooms = models.CharField(max_length = 210,choices = ROOM_CHOICES,default = '1')
	BATHROOM_CHOICES = (
	('1','1'),
	('2','2'),
	('3','3'),
	('4','4'),
	)
	bathroom = models.CharField(max_length = 210,choices = BATHROOM_CHOICES,default = '2')
	address = models.CharField(max_length = 210,default = 'None')

	STATE_CHOICES = (
		('CA','California'),
		('NY','New york'),
		('C','Chicago'),

		)

	state = models.CharField(max_length = 210,default = 'None',choices = STATE_CHOICES)
	code = models.CharField(max_length = 210,default = 'None')
	images = models.ImageField(upload_to = 'images',default = 'images/20190327_154648_0001.png')
	info = models.TextField(max_length = 1000,default = 'None')
	parking = models.BooleanField(default = False,verbose_name = 'Parking')
	air = models.BooleanField(default = False)
	swimming = models.BooleanField(default = False)
	laundry = models.BooleanField(default = False)
	dealer_name = models.CharField(max_length = 210,default = 'None')
	dealer_email = models.EmailField(max_length = 210,default = 'abc@gmail.com')
	dealer_number = models.CharField(max_length = 210,default = 'Not mentioned')
	user = models.ForeignKey(User,related_name = 'user',default = True)
	timpestamp = models.DateTimeField(auto_now_add = True)
	category = models.ManyToManyField(Category,related_name = 'categories',default = None)


	def get_absolute_url(self,*args,**kwargs):
		return reverse('profile_details:property')

	def __str__(self):
		return self.title

properties/forms.py
from django import forms
from .models import Property

class Property_Form(forms.ModelForm):
	class Meta:
		model = Property
		fields = ('title','status','price','area','rooms','bathroom','address','state','code','images',
		'info','dealer_name','dealer_email','dealer_number','air','parking','swimming','laundry','category',)


		widgets = {
		    'parking': forms.CheckboxInput(attrs={'id':'checkbox1',}),
		    'air': forms.CheckboxInput(attrs={'id':'checkbox2',}),
		    'swimming': forms.CheckboxInput(attrs={'id':'checkbox4',}),
		    'laundry': forms.CheckboxInput(attrs={'id':'checkbox5',}),
		    'title': forms.TextInput(attrs={'class':'input-text',}),
		    'status': forms.Select(attrs={'class':'selectpicker search-fields',}),
		    'price': forms.NumberInput(attrs={'class':'input-text',}),
		    'images': forms.ClearableFileInput(attrs={'class':'custom-file-input',}),
		    'area': forms.TextInput(attrs={'class':'input-text',}),
		    'rooms': forms.Select(attrs={'class':'selectpicker search-fields',}),
		    'bathroom': forms.Select(attrs={'class':'selectpicker search-fields',}),
		    'address': forms.TextInput(attrs={'class':'input-text',}),
		    'state': forms.Select(attrs={'class':'selectpicker search-fields',}),
		    'code': forms.TextInput(attrs={'class':'input-text',}),
		    'info': forms.TextInput(attrs={'class':'input-text','placeholder':'Detailed Information','height':'500px',}),
		    'dealer_name': forms.TextInput(attrs={'class':'input-text','placeholder':'Name'}),
		    'dealer_email': forms.EmailInput(attrs={'class':'input-text','placeholder':'Email Address'}),
		    'dealer_number': forms.TextInput(attrs={'class':'input-text','placeholder':'Phone Number'}),
		    'category': forms.SelectMultiple(attrs={'class':'selectpicker search-fields',}),
	

		}

properties/views.py
from django.shortcuts import render
from django.views import generic
from . import models
from . import forms
from django.db.models import Count
from .filters import UserFilter
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.db.models import Q

# Create your views here.

def get_category_count():
	queryset = models.Property.objects.values('category__title').annotate(Count('category'))	
	return queryset





def Properties_Category_List(request,pk):
	category = models.Category.objects.all()


	category_count = get_category_count()

	most_recent = models.Property.objects.order_by('-timpestamp')[:2]

	model = models.Property.objects.filter(category__pk=int(pk))

	paginator = Paginator(model,3)
	page_var = 'list'
	page = request.GET.get(page_var)

	try:
		paginated_queryset = paginator.page(page)
	except PageNotAnInteger:
		paginated_queryset = paginator.page(1)
	except EmptyPage:
		paginated_queryset = paginator.page(page)

	index = paginated_queryset.number - 1 
	max_index = len(paginator.page_range)
	start_index = index - 3 if index >= 3 else 0
	end_index = index + 3 if index <= max_index - 3 else max_index
	page_range = list(paginator.page_range)[start_index:end_index]

	
	context = {
		"property":paginated_queryset,
		'page_var':page_var,
		'page_range':page_range,
		'most_recent':most_recent,
		'category_count':category_count,
		'category':category
		}

	template_name = 'properties/properties_category_list.html'	
	return render(request,template_name,context)





def Properties_List(request):
	category = models.Category.objects.all()

	category_count = get_category_count()
	most_recent = models.Property.objects.order_by('-timpestamp')[:2]
	model = models.Property.objects.all()

	

	paginator = Paginator(model,3)
	page_var = 'list'
	page = request.GET.get(page_var)


	try:
		paginated_queryset = paginator.page(page)
	except PageNotAnInteger:
		paginated_queryset = paginator.page(1)
	except EmptyPage:
		paginated_queryset = paginator.page(page)

	index = paginated_queryset.number - 1 
	max_index = len(paginator.page_range)
	start_index = index - 3 if index >= 3 else 0
	end_index = index + 3 if index <= max_index - 3 else max_index
	page_range = list(paginator.page_range)[start_index:end_index]

	context = {
		"property":paginated_queryset,
		'page_var':page_var,
		'page_range':page_range,
		'most_recent':most_recent,
		'category_count':category_count,
		'category': category
		}

	template_name = 'properties/properties_list.html'	
	return render(request,template_name,context)	






class Property_detail(generic.DetailView):
	model = models.Property
	template_name = 'properties/property_detail.html'




def search(request):
	model = models.Property.objects.all()
	most_recent = models.Property.objects.order_by('-timpestamp')[:2]
	query1 = request.GET.get('q1')
	query2 = request.GET.get('q2')
	query3 = request.GET.get('q3')
	query4 = request.GET.get('q4')

	paginator = Paginator(model,3)
	page_var = 'list'
	page = request.GET.get(page_var)


	try:
		paginated_queryset = paginator.page(page)
	except PageNotAnInteger:
		paginated_queryset = paginator.page(1)
	except EmptyPage:
		paginated_queryset = paginator.page(page)

	index = paginated_queryset.number - 1 
	max_index = len(paginator.page_range)
	start_index = index - 3 if index >= 3 else 0
	end_index = index + 3 if index <= max_index - 3 else max_index
	page_range = list(paginator.page_range)[start_index:end_index]

	if query1:
		model = model.filter(
				  Q(status__icontains=query1)|
				  Q(address__icontains=query2)|
				  Q(rooms__icontains=query3)| 
				  Q(bathroom__icontains=query4)
				  
				  ).distinct(
				  )
	return render(request,'properties/properties_search_list.html',{'property':paginated_queryset,'page_var':page_var,
		'page_range':page_range,'most_recent':most_recent})

		

	

properties/templates/properties/properties_category_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'header.html' %}

<!-- Sub banner start -->
<div class="sub-banner overview-bgi">
	<div class="container">
		<div class="breadcrumb-area">
			<h1>Properties Listing</h1>
			<ul class="breadcrumbs">
				<li><a href="{% url 'index' %}">Home</a></li>
				<li class="active">Properties Listing</li>
			</ul>
		</div>
	</div>
</div>
<!-- Sub Banner end -->


  </ul>
<!-- Properties section start -->
<div class="properties-section content-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-md-12">
				<div class="sidebar-left">
					<!-- Advanced search start -->
					<form method="get" >
					<div class="widget advanced-search">
						<h3 class="sidebar-title">Advanced Search</h3>
						<div class="s-border"></div>
						<form method="GET">
							<div class="form-group">
								<select class="selectpicker search-fields" name="all-status" name="q" >
									<option>All Status</option>
									<option>For Sale</option>
									<option>For Rent</option>
								</select>
							</div>
							<div class="form-group">
								<select class="selectpicker search-fields" name="location" name="q" >
									<option>location</option>
									<option>California</option>
									<option>American Samoa</option>
									<option>Belgium</option>
									<option>Canada</option>
								</select>
							</div>
							<div class="row">
								<div class="col-lg-6 col-md-6 col-sm-6">
									<div class="form-group">
										<select class="selectpicker search-fields" name="bedrooms" name="q" >
											<option>Bedrooms</option>
											<option>1</option>
											<option>2</option>
											<option>3</option>
											<option>4</option>
										</select>
									</div>
								</div>
								<div class="col-lg-6 col-md-6 col-sm-6">
									<div class="form-group">
										<select class="selectpicker search-fields" name="bathroom" name="q" >
											<option>Bathroom</option>
											<option>1</option>
											<option>2</option>
											<option>3</option>
											<option>4</option>
										</select>
									</div>
								</div>
							</div>
							<div class="range-slider">
								<label>Area</label>
								<div data-min="0" data-max="10000" data-min-name="min_area" data-max-name="max_area" data-unit="Sq ft" class="range-slider-ui ui-slider" aria-disabled="false" name="q" ></div>
								<div class="clearfix"></div>
							</div>
							<div class="range-slider">
								<label>Price</label>
								<div data-min="0" data-max="150000"  data-min-name="min_price" data-max-name="max_price" data-unit="USD" class="range-slider-ui ui-slider" aria-disabled="false" name="q" ></div>
								<div class="clearfix"></div>
							</div>
							<div class="form-group mb-0">
								<input  type="submit" class="search-button">Search</input>
							</div>
						</form>
					</div>
					<!-- Recent properties start -->
					<h3 class="sidebar-title">Recent Properties</h3>
					{% for i in most_recent %}
					<div class="widget recent-properties">
						<div class="s-border"></div>
						<div class="media mb-4">
							<a class="pr-3" href="{% url 'property:detail' i.pk %}">
								<img class="media-object" src="{{i.images.url}}" alt="small-properties">
							</a>
							<div class="media-body align-self-center">
								<h5>
									<a href="{% url 'property:detail' i.pk %}">{{i.title}}</a>
								</h5>
								<div class="listing-post-meta">
									${{i.price}} | <a href="#"><i class="fa fa-calendar"></i> {{i.timestamp}} </a>
								</div>
							</div>
						</div>
					</div>
					{% endfor %}
					<!-- Posts by category Start -->

					<div class="posts-by-category widget">
						<h3 class="sidebar-title">Category</h3>
						<div class="s-border"></div>

		
						<ul class="list-unstyled list-cat breadcrumbs">
							{% for i in category %}
							 <li><a href="{% url 'property:category' i.pk %}" class="nav-link">{{ i.title }}</a><br></li>
							{% endfor %}			
						</ul>
						

					</div>


					<!-- Our agent sidebar start -->

				</div>
			</div>
			<div class="col-lg-8 col-md-12">
				<!-- Option bar start -->
				<div class="option-bar d-none d-xl-block d-lg-block d-md-block d-sm-block">
					<div class="row">
						<div class="col-lg-6 col-md-7 col-sm-7">
							<div class="sorting-options2">
								<span class="sort">Sort by:</span>
								<select class="selectpicker search-fields" name="default-order">
									<option>Default Order</option>
									<option>Price High to Low</option>
									<option>Price: Low to High</option>
									<option>Newest Properties</option>
									<option>Oldest Properties</option>
								</select>
							</div>
						</div>
						<div class="col-lg-6 col-md-5 col-sm-5">
							<div class="sorting-options">
								<a href="properties-list-leftsidebar.html" class="change-view-btn active-view-btn"><i class="fa fa-th-list"></i></a>
								<a href="properties-grid-leftside.html" class="change-view-btn"><i class="fa fa-th-large"></i></a>
							</div>
						</div>
					</div>
				</div>
				<!-- Property box 2 start -->
				{% for u in property %}
				<div class="property-box-2" >
					<div class="row">
						<div class="col-lg-5 col-md-5 col-pad">
							<div class="property-thumbnail">
								<a href="{% url 'property:detail' u.pk %}" class="property-img">
									<img src="{{u.images.url}}" alt="properties" class="img-fluid">
									<div class="listing-badges">
										<span class="featured">Featured</span>
									</div>
									<div class="price-box"><span>${{u.price}}</span> Per month</div>
								</a>
							</div>
						</div>
						<div class="col-lg-7 col-md-7 col-pad">
							<div class="detail">
								<div class="hdg">
									<h3 class="title">
										<a href="{% url 'property:detail' u.pk %}">{{u.title}}</a>
									</h3>
									<h5 class="location">
										<a href="{% url 'property:detail' u.pk %}">
											<i class="flaticon-pin"></i>{{u.address}}.{{u.state}}
										</a>
									</h5>
								</div>
								<ul class="facilities-list clearfix">
									<li>
										<span>Area</span>{{u.area}} Sqft
									</li>
									<li>
										<span>Rooms</span> {{u.rooms}}
									</li>
									<li>
										<span class="mt-2">Baths</span> {{u.bathroom}}
									</li>
								</ul>
								
								<div class="footer">
									<a href="#" tabindex="0">
										<i class="flaticon-people pt-3"></i>{{u.dealer_name}}
									</a>
									<a href="#" tabindex="0">
										<i class="flaticon-people pt-3"></i>
									</a>
									
								</div>
							</div>
						</div>
					</div>
				</div>
				{% endfor %}
				<!-- Page navigation start -->
				<div class="pagination-box hidden-mb-45 text-center">
					<nav aria-label="Page navigation example">

						<ul class="pagination">

							{% if property.has_previous %}
							<li class="page-item">
								<a class="page-link" href="?{{page_var}}={{property.previous_page_number}}">Prev</a>
							</li>
							{% endif %}

							{% for i in page_range %}
							{% if property.number == i %}
							<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
							{% else %}
							<li><a href="?{{page_var}}={{ i }}">{{ i }}</a></li>
							{% endif %}
							{% endfor %}
							
							{% if property.has_next %}
							<li class="page-item">
								<a class="page-link" href="?{{page_var}}={{property.next_page_number}}">Next</a>
							</li>
							{% endif %}
						</ul>
					</nav>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Properties section end -->

<!-- Footer start -->

<!-- Full Page Search -->
<div id="full-page-search">
	<button type="button" class="close">×</button>
	<form action="http://themevessel-item.s3-website-us-east-1.amazonaws.com/neer/index.html#">
		<input type="search" value="" placeholder="type keyword(s) here" />
		<button type="submit" class="btn btn-sm button-theme">Search</button>
	</form>
</div>

{% endblock %}

properties/templates/properties/properties_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'header.html' %}

<!-- Sub banner start -->
<div class="sub-banner overview-bgi">
	<div class="container">
		<div class="breadcrumb-area">
			<h1>Properties Listing</h1>
			<ul class="breadcrumbs">
				<li><a href="{% url 'index' %}">Home</a></li>
				<li class="active">Properties Listing</li>
			</ul>
		</div>
	</div>
</div>
<!-- Sub Banner end -->


  </ul>

{% include 'properties/properties_same.html' %}



{% endblock %}

properties/templates/properties/properties_same.html
<!-- Properties section start -->
<div class="properties-section content-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-md-12">
				<div class="sidebar-left">
                    <!-- Advanced search start -->
                     <!-- Advanced search start -->

                    <form method="get"  action="{% url 'property:search' %}" class="pt-3 px-3">

                        <h3 class="sidebar-title">Advanced Search</h3>
                        <div class="s-border"></div>

                            <div class="form-group">
                                <select class="selectpicker search-fields"  name="q1" >
                                    <option>All Status</option>
                                    <option>For Sale</option>
                                    <option>For Rent</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <select class="selectpicker search-fields"  name="q2" >
                                    <option>location</option>
                                    <option>California</option>
                                    <option>New york</option>
                                    <option>Chicago</option>
                                  
                                </select>
                            </div>
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="form-group">
                                        <select class="selectpicker search-fields" name="q3" >
                                            <option>Rooms</option>
                                            <option>1</option>
                                            <option>2</option>
                                            <option>3</option>
                                            <option>4</option>
                                            <option>More</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="form-group">
                                        <select class="selectpicker search-fields"  name="q4" >
                                            <option>Bathroom</option>
                                            <option>1</option>
                                            <option>2</option>
                                            <option>3</option>
                                            <option>4</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        
                            <div class="form-group mb-0">
                                <input  type="submit" class="search-button" value="Search">
                            </div>

                        </form>

                    <!-- Recent properties start -->
                    <h3 class="sidebar-title pt-3 pl-3">Recent Properties</h3>
                    {% for i in most_recent %}
                    <div class="widget recent-properties">
                        <div class="s-border"></div>
                        <div class="media mb-4">
                            <a class="pr-3" href="properties-details.html">
                                <img class="media-object" src="{{i.images.url}}" alt="small-properties">
                            </a>
                            <div class="media-body align-self-center">
                                <h5>
                                    <a href="{% url 'property:detail' i.pk %}">{{i.title}}</a>
                                </h5>
                                <div class="listing-post-meta">
                                    ${{i.price}} | <a href="#"><i class="fa fa-calendar"></i> {{i.timestamp}} </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <!-- Posts by category Start -->

                    <div class="posts-by-category widget">
                        <h3 class="sidebar-title">Category</h3>
                        <div class="s-border"></div>


                        <ul class="list-unstyled list-cat breadcrumbs">
                            {% for i in category %}
                             <li><a href="{% url 'property:category' i.pk %}" class="nav-link">{{ i.title }}</a><br></li>
                            {% endfor %}            
                        </ul>


                    </div>


                    <!-- Our agent sidebar start -->






                    <!-- Our agent sidebar start -->

                </div> 
			</div>
			<div class="col-lg-8 col-md-12">
				<!-- Option bar start -->
				<!-- <div class="option-bar d-none d-xl-block d-lg-block d-md-block d-sm-block">
					<div class="row">
						<div class="col-lg-6 col-md-7 col-sm-7">
							<div class="sorting-options2">
								<span class="sort">Sort by:</span>
								<select class="selectpicker search-fields" name="default-order">
									<option>Default Order</option>
									<option>Price High to Low</option>
									<option>Price: Low to High</option>
									<option>Newest Properties</option>
									<option>Oldest Properties</option>
								</select>
							</div>
						</div>
						<div class="col-lg-6 col-md-5 col-sm-5">
							<div class="sorting-options">
								<a href="properties-list-leftsidebar.html" class="change-view-btn active-view-btn"><i class="fa fa-th-list"></i></a>
								<a href="properties-grid-leftside.html" class="change-view-btn"><i class="fa fa-th-large"></i></a>
							</div>
						</div>
					</div>
				</div> -->
				<!-- Property box 2 start -->
				{% for u in property %}
				<div class="property-box-2" >
					<div class="row">
						<div class="col-lg-5 col-md-5 col-pad">
							<div class="property-thumbnail">
								<a href="{% url 'property:detail' u.pk %}" class="property-img">
									<img src="{{u.images.url}}" alt="properties" class="img-fluid">
									<div class="listing-badges">
										<span class="featured">Featured</span>
									</div>
									<div class="price-box"><span>${{u.price}}</span> Per month</div>
								</a>
							</div>
						</div>
						<div class="col-lg-7 col-md-7 col-pad">
							<div class="detail">
								<div class="hdg">
									<h3 class="title">
										<a href="{% url 'property:detail' u.pk %}">{{u.title}}</a>
									</h3>
									<h5 class="location">
										<a href="{% url 'property:detail' u.pk %}">
											<i class="flaticon-pin"></i>{{u.address}}.{{u.state}}
										</a>
									</h5>
								</div>
								<ul class="facilities-list clearfix">
									<li>
										<span>Area</span>{{u.area}} Sqft
									</li>
									<li>
										<span>Rooms</span> {{u.rooms}}
									</li>
									<li>
										<span class="mt-2">Baths</span> {{u.bathroom}}
									</li>
								</ul>
								
								<div class="footer">
									<a href="#" tabindex="0">
										<i class="flaticon-people pt-3"></i>{{u.dealer_name}}
									</a>
									<a href="#" tabindex="0">
										<i class="flaticon-people pt-3"></i>
									</a>
									
								</div>
							</div>
						</div>
					</div>
				</div>
				{% endfor %}
				<!-- Page navigation start -->
				<div class="pagination-box hidden-mb-45 text-center">
					<nav aria-label="Page navigation example">

						<ul class="pagination">

							{% if property.has_previous %}
							<li class="page-item">
								<a class="page-link" href="?{{page_var}}={{property.previous_page_number}}">Prev</a>
							</li>
							{% endif %}

							{% for i in page_range %}
							{% if property.number == i %}
							<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
							{% else %}
							<li><a href="?{{page_var}}={{ i }}">{{ i }}</a></li>
							{% endif %}
							{% endfor %}
							
							{% if property.has_next %}
							<li class="page-item">
								<a class="page-link" href="?{{page_var}}={{property.next_page_number}}">Next</a>
							</li>
							{% endif %}
						</ul>
					</nav>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Properties section end -->

properties/templates/properties/properties_search_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'header.html' %}

<!-- Sub banner start -->
<div class="sub-banner overview-bgi">
	<div class="container">
		<div class="breadcrumb-area">
			<h1>Search Results</h1>
			<ul class="breadcrumbs">
				<li><a href="{% url 'index' %}">Home</a></li>
				<li class="active">Search Results</li>
			</ul>
		</div>
	</div>
</div>
<!-- Sub Banner end -->


  </ul>

{% include 'properties/properties_same.html' %}



{% endblock %}

properties/templates/properties/property_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'header.html' %}
<!-- Sub banner start -->
<div class="sub-banner overview-bgi">
	<div class="container">
		<div class="breadcrumb-area">
			<h1>Properties Detail</h1>
			<ul class="breadcrumbs">
				<li><a href="{% url 'index' %}">Home</a></li>
				<li class="active">Properties Detail</li>
			</ul>
		</div>
	</div>
</div>
<!-- Sub Banner end -->


<div class="row">

	<div class="col-md-6">
		<div class="container pt-3 pb-3 pl-2">
			<img src="{{object.images.url}}" class="img-fluid" style="border-radius: 1%;">
		</div>
	</div>

	<div class="col-md-6">
		<div class="container pt-3">
			<h2>{{object.title}}</h2>
			<p>{{object.status}}</p>
			<p>{{object.info}}</p>

			<div class="row">
				<div class="col-md-4">
					<h3>{{object.parking.label}}</h3>
				</div>
				<div class="col-md-4"></div>
				<div class="col-md-4"></div>
				<div class="col-md-4"></div>
			</div>

		<div class="row">
			<div class="col-md-4">
				<span><p>Dealer name: {{object.dealer_name}}</p></span>
			</div>
			<div class="col-md-4">
				<span><p>Email: {{object.dealer_email}}</p></span>
			</div>
			<div class="col-md-4">
				<span><p>Number: {{object.dealer_number}}</p></span>
			</div>
		</div>

		<div class="row">
			<div class="col-md-4">
				<span><p><strong>Address: </strong>{{object.address}}</p></span>
			</div>
			<div class="col-md-4">
				<span><p><strong>State: </strong> {{object.state}}</p></span>
			</div>
			<div class="col-md-4">
				<span><p><strong>Pincode: </strong> {{object.code}}</p></span>
			</div>
		</div>

		<div class="row">
			<div class="col-md-4">
				<span><p><strong>Price: </strong>${{object.price}}</p></span>
			</div>
			<div class="col-md-4">
				<span><p><strong>Rooms: </strong>{{object.rooms}}</p></span>
			</div>
			<div class="col-md-4">
				<span><p><strong>Bathroom: </strong> {{object.bathroom}}</p></span>
			</div>
		</div>

		</div>
	</div>
</div>


{% endblock %}