profile_details/urls.py
from django.conf.urls import url
from . import views

app_name = "profile_details"

urlpatterns = [

url(r'^property/$',views.Profile_Properties_List,name = "property"),
url(r'^signup/',views.SignUp.as_view(),name = 'signup'),
url(r'^submit/(?P<pk>[-\w]+)/$',views.Submit_Property.as_view(),name = "submit"),
url(r'^update/(?P<pk>[-\w]+)/$',views.Update_Property.as_view(),name = "update"),
url(r'^delete/(?P<pk>[-\w]+)/$',views.Delete_Property.as_view(),name = "delete"),



]

properties/urls.py
from django.conf.urls import url
from . import views

app_name = 'property'

urlpatterns = [


url(r'^list/$',views.Properties_List,name = "list"),

url(r'^search/$',views.search,name = "search"),

url(r'^category/(?P<pk>[-\w]+)/$',views.Properties_Category_List,name = "category"),

url(r'^detail/(?P<pk>[-\w]+)/$',views.Property_detail.as_view(),name = "detail"),

]

realestate/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from django.conf.urls.static import static
from . import settings 
from profile_details.views import SignUp


urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^accounts/', include('django.contrib.auth.urls')), 
	url(r'^profile/',include('profile_details.urls')),
	url(r'^property/',include('properties.urls')),
	url(r'^$',views.Home,name = 'index'),
	url(r'^about/$',views.About,name = 'about'),
	url(r'^success/$',views.success,name = 'success'),

	
] 
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profile_details/models.py
from django.db import models

# Create your models here.

profile_details/forms.py
from django import forms
from django.contrib.auth.models import User

class CustomUserCreationForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('username','password')
		
		widgets = {
			'username': forms.TextInput(attrs={'class': 'form-control','placeholder':'username'}),
			'password': forms.TextInput(attrs={'class': 'form-control','placeholder':'passowrd'}),
			}

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)

		for fieldname in ['username']:
			self.fields[fieldname].help_text = None


		

profile_details/views.py
from django.shortcuts import render
from django.views import generic 
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from properties import models
from properties import forms
# Create your views here.
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin

def Profile_Properties_List(request):
	properties = models.Property.objects.filter(user=request.user)
	return render(request, 'profile_details/my-properties.html', {'property': properties})

	
class SignUp(generic.CreateView):
	form_class = UserCreationForm
	success_url = reverse_lazy('login')
	template_name = 'profile_details/signup.html'



class Submit_Property(generic.CreateView,LoginRequiredMixin):
	model = models.Property
	form_class = forms.Property_Form
	template_name = 'profile_details/submit-property.html'
	def form_valid(self, form):
		form.instance.user = self.request.user
		form.save()
		return super().form_valid(form)





class Update_Property(generic.UpdateView,LoginRequiredMixin):
	model = models.Property
	form_class = forms.Property_Form
	template_name = 'profile_details/submit-property.html'

class Delete_Property(generic.DeleteView,LoginRequiredMixin):
	model = models.Property
	form_class = forms.Property_Form
	template_name = 'profile_details/delete-property.html'
		
	def get_success_url(self, **kwargs):
	# obj = form.instance or self.object
		return reverse_lazy("profile_details:property", kwargs={'pk': self.object.pk})

profile_details/templates/profile_details/bookings.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<!-- Dashboard start -->
<div class="dashboard submit-property">
    <div class="container-fluid ">
        <div class="row">
            <div class="col-lg-3 col-md-12 col-sm-12 col-pad">
                <div class="dashboard-nav d-none d-xl-block d-lg-block">
                    {% include 'profile_details/side-menu.html' %}
                </div>
            </div>
            <div class="col-lg-9 col-md-12 col-sm-12 col-pad">
                <div class="content-area5 dashboard-content">
                    {% include 'profile_details/uper-menu.html' %}
                    <div class="submit-address dashboard-list">
                        <form method="GET">
                            <h4>Bookings List</h4>
                            <div class="row pad-20">
                                <div class="col-lg-12">
                                    <div class="comment">
                                        <div class="comment-author">
                                            <a href="#">
                                                <img src="img/avatar/avatar-1.jpg" alt="comments-user">
                                            </a>
                                        </div>
                                        <div class="comment-content">
                                            <div class="comment-meta">
                                                <h5>Maikel Alisa</h5>
                                                <div class="comment-meta">
                                                    8:42 PM 1/28/2017<a href="#">Reply</a>
                                                </div>
                                            </div>
                                            <ul>
                                                <li>Item :<span> Real Luxury Villa</span></li>
                                                <li>Start date : <span> 18 November 2018</span></li>
                                                <li>End date : <span> 18 November 2018</span></li>
                                                <li>Booking details :<span> 4 Peoples</span></li>
                                                <li>Mail : <span><a href="mailto:info@themevessel.com"> info@themevessel.com</a> </span></li>
                                                <li>Phone : <span> <a href="tel:+79617036705">+79617036705</a></span></li>
                                            </ul>
                                            <div class="buttons mb-20">
                                                <a href="#" class="btn-1 btn-gray"><i class="fa fa-fw fa-check-circle-o"></i> Approve</a>
                                                <a href="#" class="btn-1 btn-gray"><i class="fa fa-fw fa-times-circle-o"></i> Cancel</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="comment">
                                        <div class="comment-author">
                                            <a href="#">
                                                <img src="img/avatar/avatar-2.jpg" alt="comments-user">
                                            </a>
                                        </div>
                                        <div class="comment-content">
                                            <div class="comment-meta">
                                                <h5>Teseira</h5>
                                                <div class="comment-meta">
                                                    8:42 PM 1/28/2017<a href="#">Reply</a>
                                                </div>
                                            </div>
                                            <ul>
                                                <li>Item :<span> Real Luxury Villa</span></li>
                                                <li>Start date : <span> 18 November 2018</span></li>
                                                <li>End date : <span> 18 November 2018</span></li>
                                                <li>Booking details :<span> 4 Peoples</span></li>
                                                <li>Mail : <span><a href="mailto:info@themevessel.com"> info@themevessel.com</a> </span></li>
                                                <li>Phone : <span> <a href="tel:+79617036705">+79617036705</a></span></li>
                                            </ul>
                                            <div class="buttons mb-20">
                                                <a href="#" class="btn-1 btn-gray"><i class="fa fa-fw fa-check-circle-o"></i> Approve</a>
                                                <a href="#" class="btn-1 btn-gray"><i class="fa fa-fw fa-times-circle-o"></i> Cancel</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="comment comment-b">
                                        <div class="comment-author">
                                            <a href="#">
                                                <img src="img/avatar/avatar-4.jpg" alt="comments-user">
                                            </a>
                                        </div>
                                        <div class="comment-content">
                                            <div class="comment-meta">
                                                <h5>Emma Connor</h5>
                                                <div class="comment-meta">
                                                    8:42 PM 1/28/2017<a href="#">Reply</a>
                                                </div>
                                            </div>
                                            <ul>
                                                <li>Item :<span> Real Luxury Villa</span></li>
                                                <li>Start date : <span> 18 November 2018</span></li>
                                                <li>End date : <span> 18 November 2018</span></li>
                                                <li>Booking details :<span> 4 Peoples</span></li>
                                                <li>Mail : <span><a href="mailto:info@themevessel.com"> info@themevessel.com</a> </span></li>
                                                <li>Phone : <span> <a href="tel:+79617036705">+79617036705</a></span></li>
                                            </ul>
                                            <div class="buttons">
                                                <a href="#" class="btn-1 btn-gray"><i class="fa fa-fw fa-check-circle-o"></i> Approve</a>
                                                <a href="#" class="btn-1 btn-gray"><i class="fa fa-fw fa-times-circle-o"></i> Cancel</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <p class="sub-banner-2 text-center">© 2018 Theme Vessel. Trademarks and brands are the property of their respective owners.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Dashboard end -->

<!-- Full Page Search -->
<div id="full-page-search">
    <button type="button" class="close">×</button>
    <form action="http://themevessel-item.s3-website-us-east-1.amazonaws.com/neer/index.html#">
        <input type="search" value="" placeholder="type keyword(s) here" />
        <button type="submit" class="btn btn-sm button-theme">Search</button>
    </form>
</div>

{% endblock %}

profile_details/templates/profile_details/delete-property.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <div class="container">
    <h3 class="mt-2">Are you sure that you wanna delete<span style="color: #e20f59;"> "{{ object }}"</span></h3>
    <input type="submit" value='Delete Property' class="btn btn-danger mb-4">
    </div>
</form>
{% endblock %}

profile_details/templates/profile_details/my-properties.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<!-- Dashboard start -->
<div class="dashboard">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-3 col-md-12 col-sm-12 col-pad">
                <div class="dashboard-nav d-none d-xl-block d-lg-block">
                     {% include 'profile_details/side-menu.html' %}
                </div>
            </div>
            <div class="col-lg-9 col-md-12 col-sm-12 col-pad">
                <div class="content-area5">
                    <div class="dashboard-content">
                      {% include 'profile_details/uper-menu.html' %}
                        <div class="dashboard-list">
                            <h3>My Properties List</h3>

                            {% for i in property.all %}
                            <table class="manage-table">
                                <tbody>
                                <tr class="responsive-table">
                                    <td class="listing-photoo">
                                        <img src="{{i.images.url }}" class="image-fluid">
                                    </td>
                                    <td class="title-container">
                                        <h2><a href="#">{{i.title}}</a></h2>
                                        <h5 class="d-none d-xl-block d-lg-block d-md-block"><i class="flaticon-pin"></i>{{i.address}}.{{i.state}}, </h5>
                                        <h6 class="table-property-price">${{i.price}} / monthly</h6>
                                    </td>
                                    <td class="action">
                                        <a href="{% url 'profile_details:update' i.pk %}"><i class="fa fa-pencil"></i> Edit</a>
                                        <a href="{% url 'profile_details:delete' i.pk %}" class="delete"><i class="fa fa-remove"></i>Delete</a>
                                    </td>
                                </tr>
                                </tbody>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                    <p class="sub-banner-2 text-center">© 2019 Designed and developed by Ubaid Parvaiz</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Dashboard end -->

<!-- Full Page Search -->
<div id="full-page-search">
    <button type="button" class="close">×</button>
    <form action="http://themevessel-item.s3-website-us-east-1.amazonaws.com/neer/index.html#">
        <input type="search" value="" placeholder="type keyword(s) here" />
        <button type="submit" class="btn btn-sm button-theme">Search</button>
    </form>
</div>

{% endblock %}

profile_details/templates/profile_details/side-menu.html
 <div class="dashboard-inner">
    <h4>Listings</h4>
    <ul>
        <li><a href="{% url 'profile_details:property' %}"><i class="flaticon-apartment-1"></i>My Properties</a></li>
        <li class="active"><a href="{% url 'profile_details:submit' user.pk %}"><i class="flaticon-plus"></i>Submit Property</a></li>
    </ul>
    <h4>Account</h4>
    <ul>
        <li><a href="{% url 'logout' %}"><i class="flaticon-logout"></i>Logout</a></li>
    </ul>
</div>

profile_details/templates/profile_details/signup.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'header.html' %}

<!-- Contact section start -->
<div class="contact-section overview-bgi">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <!-- Form content box start -->
                <div class="form-content-box">
                    <!-- details -->
                    <div class="details">
                        <!-- Logo -->
                        <a href="index-2.html">
                            <img src="{% static 'properties/img/black-logo.png' %}" class="cm-logo" alt="black-logo">
                        </a>
                        <!-- Name -->
                        <h3>Sign up </h3>
                        <!-- Form start -->
                        <form method="Post">
                            {% csrf_token %}                        
                            {{form|crispy}}
                            <div class="form-group mb-0">
                                <input type="submit" class="btn-md button-theme btn-block" value="Signup"></input>
                            </div>
                        </form>
                        <!-- Social List -->
                        <ul class="social-list clearfix">
                            <li><a href="#" class="facebook-bg"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#" class="twitter-bg"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#" class="google-bg"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="#" class="linkedin-bg"><i class="fa fa-linkedin"></i></a></li>
                        </ul>
                    </div>
                    <!-- Footer -->
                    <div class="footer">
                        <span>Already a member? <a href="{% url 'login' %}">Login here</a></span>
                    </div>
                </div>
                <!-- Form content box end -->
            </div>
        </div>
    </div>
</div>
<!-- Contact section end -->

<!-- Full Page Search -->
<div id="full-page-search">
    <button type="button" class="close">×</button>
    <form action="http://themevessel-item.s3-website-us-east-1.amazonaws.com/neer/index.html#">
        <input type="search" value="" placeholder="type keyword(s) here" />
        <button type="submit" class="btn btn-sm button-theme">Search</button>
    </form>
</div>
{% endblock %}

profile_details/templates/profile_details/submit-property.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!-- Dashboard start -->
<div class="dashboard submit-property">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-3 col-md-12 col-sm-12 col-pad">
                <div class="dashboard-nav d-none d-xl-block d-lg-block">
                 {% include 'profile_details/side-menu.html' %}
             </div>
         </div>

        <div class="col-lg-9 col-md-12 col-sm-12 col-pad">
            <div class="content-area5 dashboard-content">
              {% include 'profile_details/uper-menu.html' %}
              <div class="submit-address dashboard-list">
                <form method="post" enctype="multipart/form-data">
                    {%csrf_token%}
                    <h4 class="bg-grea-3">Basic Information</h4>
                    <div class="search-contents-sidebar">
                        <div class="row pad-20">
                            <div class="col-lg-4 col-md-4 col-sm-12">
                                <div class="form-group">
                                    <label>Property Title</label>
                                    {{form.title}}

                                </div>
                            </div>
                            <div class="col-lg-4 col-md-4 col-sm-12">
                                <div class="form-group">
                                    <label>Status</label>
                                    {{form.status}}
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-4 col-sm-12">
                                <div class="form-group">
                                    <label>Price</label>
                                    {{form.price}}
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-4 col-sm-12">
                                <div class="form-group">
                                    <label>Area/Location</label>
                                    {{form.area}}
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-4 col-sm-12">
                                <div class="form-group">
                                    <label>Rooms</label>
                                    {{form.rooms}}
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-4 col-sm-12">
                                <div class="form-group">
                                    <label>Bathroom</label>
                                    {{form.bathroom}}
                                </div>
                            </div>
                        </div>
                    </div>
                    <h4 class="bg-grea-3">Location</h4>
                    <div class="row pad-20">
                        <div class="col-lg-4 col-md-4 col-sm-12">
                            <div class="form-group">
                                <label>Address</label>
                                {{form.address}}
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-12">
                            <div class="form-group">
                                <label>State</label>
                                {{form.state}}
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-12">
                            <div class="form-group">
                                <label>Postal Code</label>
                                {{form.code}}
                            </div>
                        </div>
                    </div>
                    <h4 class="bg-grea-3">Property Gallery</h4>
                    <div class="row pad-20">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{form.images}}
                                <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                            </div>    
                        </div>
                    </div> 
                    <h4 class="bg-grea-3">Detailed Information</h4>
                    <div class="row pad-20">
                        <div class="col-lg-12">
                         {{form.info}}
                     </div>
                 </div>
                 <h4 class="bg-grea-3">Features (optional)</h4>
                 <div class="row pad-20">
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="checkbox checkbox-theme checkbox-circle pl-4">
                            {{form.parking}}
                        
                            <label for="checkbox1">
                                Free Parking
                            </label>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="checkbox checkbox-theme checkbox-circle">
                            {{form.air}}
                        
                            <label for="checkbox2">
                                Air Condition
                            </label>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="checkbox checkbox-theme checkbox-circle">
                            {{form.swimming}}
                            <label for="checkbox4">
                                Swimming Pool
                            </label>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="checkbox checkbox-theme checkbox-circle">
                            {{form.laundry}}
                            <label for="checkbox5">
                                Laundry Room
                            </label>
                        </div>
                    </div>
                </div>
                <h4 class="bg-grea-3">Contact Details</h4>
                <div class="row pad-20">
                    <div class="col-lg-3 col-md-3 col-sm-12">
                        <div class="form-group">
                            <label>Name</label>
                            {{form.dealer_name}}
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-12">
                        <div class="form-group">
                            <label>Email</label>
                            {{form.dealer_email}}
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-12">
                        <div class="form-group">
                            <label>Phone (optional)</label>
                            {{form.dealer_number}}
                        </div>
                    </div> 
                    <div class="col-lg-3 col-md-3 col-sm-12">
                        <div class="form-group">
                            <label>Category</label>
                            {{form.category}}
                            {{form.errors}}
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-12 col-sm-12">
                     <input type="submit" class="btn-md button-theme btn-block" value="Submit"></input>
                 </div>
             </div>
         </form>
     </div>
     <p class="sub-banner-2 text-center">© 2018 Theme Vessel. Trademarks and brands are the property of their respective owners.</p>
 </div>
</div>
</div>
</div>
</div>
<!-- Dashboard end -->

<!-- Full Page Search -->
<div id="full-page-search">
    <button type="button" class="close">×</button>
    <form action="http://themevessel-item.s3-website-us-east-1.amazonaws.com/neer/index.html#">
        <input type="search" value="" placeholder="type keyword(s) here" />
        <button type="submit" class="btn btn-sm button-theme">Search</button>
    </form>
</div>

{% endblock %}