profile_details/urls.py
from django.conf.urls import url
from . import views

app_name = "profile_details"

urlpatterns = [

url(r'^property/$',views.Profile_Properties_List,name = "property"),
url(r'^signup/',views.SignUp.as_view(),name = 'signup'),
url(r'^submit/(?P<pk>[-\w]+)/$',views.Submit_Property.as_view(),name = "submit"),
url(r'^update/(?P<pk>[-\w]+)/$',views.Update_Property.as_view(),name = "update"),
url(r'^delete/(?P<pk>[-\w]+)/$',views.Delete_Property.as_view(),name = "delete"),



]

properties/urls.py
from django.conf.urls import url
from . import views

app_name = 'property'

urlpatterns = [


url(r'^list/$',views.Properties_List,name = "list"),

url(r'^search/$',views.search,name = "search"),

url(r'^category/(?P<pk>[-\w]+)/$',views.Properties_Category_List,name = "category"),

url(r'^detail/(?P<pk>[-\w]+)/$',views.Property_detail.as_view(),name = "detail"),

]

realestate/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from django.conf.urls.static import static
from . import settings 
from profile_details.views import SignUp


urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^accounts/', include('django.contrib.auth.urls')), 
	url(r'^profile/',include('profile_details.urls')),
	url(r'^property/',include('properties.urls')),
	url(r'^$',views.Home,name = 'index'),
	url(r'^about/$',views.About,name = 'about'),
	url(r'^success/$',views.success,name = 'success'),

	
] 
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'header.html' %}
<!-- Sub banner start -->
<div class="sub-banner overview-bgi">
    <div class="container">
        <div class="breadcrumb-area">
            <h1>About Us</h1>
            <ul class="breadcrumbs">
                <li><a href="{% url 'index' %}">Home</a></li>
                <li class="active">About Us</li>
            </ul>
        </div>
    </div>
</div>
<!-- Sub Banner end -->

<!-- About city estate start -->
<div class="about-real-estate  content-area-5">
    <div class="container">
        <div class="row">
            <div class="col-xl-6 col-lg-7 col-md-12 col-sm-12 col-xs-12">
                <div class="about-slider-box simple-slider">
                    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img class="d-block w-100" src="{% static 'properties/img/properties/properties-1.jpg' %}" alt="First slide">
                            </div>
                            <div class="carousel-item">
                                <img class="d-block w-100" src="{% static 'properties/img/properties/properties-2.jpg' %}" alt="Second slide">
                            </div>
                            <div class="carousel-item">
                                <img class="d-block w-100" src="{% static 'properties/img/properties/properties-3.jpg' %}" alt="Third slide">
                            </div>
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                            <span class="slider-mover-left slider-btn-l" aria-hidden="true">
                                <i class="fa fa-angle-left"></i>
                            </span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                            <span class="slider-mover-right slider-btn-r " aria-hidden="true">
                                 <i class="fa fa-angle-right"></i>
                            </span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-xl-6 col-lg-5 col-md-12 col-sm-12 col-xs-12">
                <div class="about-text">
                    <h3>Welcome to Logo</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero saepe corporis iusto, quae quas neque a maiores tenetur dolorum reiciendis!</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex, optio?</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- About city estate end -->

<!-- Helping sentar start -->
<div class="helping-sentar">
    <div class="container">
        <div class="row">
            <div class="col-xl-6 col-lg-6 align-self-center">
                <!-- Contact 1 start -->
                <div class="contact-2 pb-hediin-60">
                    <h5 class="clearfix">Always Support You</h5>
                    <h3 class="heading">How can we help</h3>
                    <form action="#" method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <div class="form-group name">
                                    <input type="text" name="name" class="form-control" placeholder="Name">
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <div class="form-group email">
                                    <input type="email" name="email" class="form-control" placeholder="Email">
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <div class="form-group subject">
                                    <input type="text" name="subject" class="form-control" placeholder="Subject">
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <div class="form-group number">
                                    <input type="text" name="phone" class="form-control" placeholder="Number">
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="form-group message">
                                    <textarea class="form-control" name="message" placeholder="Write message"></textarea>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                                <div class="send-btn">
                                    <input type="submit" value="Send Message" class="btn btn-md button-theme text-white"></input>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <!-- Contact 1 end -->
            </div>
            <div class="offset-xl-1 col-xl-5 col-lg-6">
                <img src="{% static 'properties/img/avatar/avatar-10.png' %}" alt="avatar-10" class="img-fluid">
            </div>
        </div>
    </div>
</div>
<!-- Helping sentar end -->

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="zxx">

{% include 'head.html' %}

<body>

	{% block content %}


	{% endblock %}
	
	{% include 'footer.html' %}


	{% include 'js.html' %}


</body>
</html>

templates/faq.html
{% extends 'base.html' %}
{% block content %}
{% include 'header.html' %}

<!-- Sub banner start --><div class="sub-banner overview-bgi">
    <div class="container">
        <div class="breadcrumb-area">
            <h1>Faq</h1>
            <ul class="breadcrumbs">
                <li><a href="index-2.html">Home</a></li>
                <li class="active">Faq</li>
            </ul>
        </div>
    </div>
</div>
<!-- Sub Banner end -->

<!-- Faq start -->
<div class="faq content-area-9">
    <div class="container">
        <!-- Main title -->
        <div class="main-title text-center">
            <h1>Faq</h1>
            <p>Got a question? We've got answers. If you have some other questions, see our support center.</p>
        </div>
        <div class="row">
            <div class="col-lg-10 offset-lg-1">
                <div id="faq" class="faq-accordion">
                    <div class="card m-b-0">
                        <div class="card-header">
                            <a class="card-title collapsed" data-toggle="collapse" data-parent="#faq" href="#collapse1">
                                How can i choose multiple tours ?
                            </a>
                        </div>
                        <div id="collapse1" class="card-block collapse">
                            <div class="p-text">
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec luctus tincidunt aliquam. Aliquam gravida massa at sem vulputate interdum et vel eros. Maecenas eros enim, tincidunt vel turpis vel, dapibus tempus nulla. Donec vel nulla dui. Pellentesque sed ante sed ligula hendrerit condimentum. Suspendisse rhoncus fringilla ipsum quis porta. Morbi tincidunt viverra pharetra. Vestibulum vel mauris et odio lobortis laoreet eget eu magna. Proin mauris erat, luctus at nulla ut, lobortis mattis magna. Morbi a arcu lacus. Maecenas tristique velit vitae nisi consectetur, in mattis diam sodales. Mauris sagittis sem mattis justo bibendum, a eleifend dolor facilisis. Mauris nec pharetra tortor, ac aliquam felis. Nunc pretium erat sed
                            </div>
                        </div>
                        <div class="card-header">
                            <a class="card-title collapsed" data-toggle="collapse" data-parent="#faq" href="#collapse2">
                                What are the safties related to tours ?
                            </a>
                        </div>
                        <div id="collapse2" class="card-block collapse">
                            <div class="p-text">
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec luctus tincidunt aliquam. Aliquam gravida massa at sem vulputate interdum et vel eros. Maecenas eros enim, tincidunt vel turpis vel, dapibus tempus nulla. Donec vel nulla dui. Pellentesque sed ante sed ligula hendrerit condimentum. Suspendisse rhoncus fringilla ipsum quis porta. Morbi tincidunt viverra pharetra. Vestibulum vel mauris et odio lobortis laoreet eget eu magna. Proin mauris erat, luctus at nulla ut, lobortis mattis magna. Morbi a arcu lacus. Maecenas tristique velit vitae nisi consectetur, in mattis diam sodales. Mauris sagittis sem mattis justo bibendum, a eleifend dolor facilisis. Mauris nec pharetra tortor, ac aliquam felis. Nunc pretium erat sed
                            </div>
                        </div>
                        <div class="card-header">
                            <a class="card-title collapsed" data-toggle="collapse" data-parent="#faq" href="#collapse3">
                                What are the safties related to tours ?
                            </a>
                        </div>
                        <div id="collapse3" class="card-block collapse">
                            <div class="p-text">
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec luctus tincidunt aliquam. Aliquam gravida massa at sem vulputate interdum et vel eros. Maecenas eros enim, tincidunt vel turpis vel, dapibus tempus nulla. Donec vel nulla dui. Pellentesque sed ante sed ligula hendrerit condimentum. Suspendisse rhoncus fringilla ipsum quis porta. Morbi tincidunt viverra pharetra. Vestibulum vel mauris et odio lobortis laoreet eget eu magna. Proin mauris erat, luctus at nulla ut, lobortis mattis magna. Morbi a arcu lacus. Maecenas tristique velit vitae nisi consectetur, in mattis diam sodales. Mauris sagittis sem mattis justo bibendum, a eleifend dolor facilisis. Mauris nec pharetra tortor, ac aliquam felis. Nunc pretium erat sed
                            </div>
                        </div>
                        <div class="card-header bd-none">
                            <a class="card-title collapsed" data-toggle="collapse" data-parent="#faq" href="#collapse4">
                                What is your refund policy ?
                            </a>
                        </div>
                        <div id="collapse4" class="card-block collapse">
                            <div class="p-text">
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec luctus tincidunt aliquam. Aliquam gravida massa at sem vulputate interdum et vel eros. Maecenas eros enim, tincidunt vel turpis vel, dapibus tempus nulla. Donec vel nulla dui. Pellentesque sed ante sed ligula hendrerit condimentum. Suspendisse rhoncus fringilla ipsum quis porta. Morbi tincidunt viverra pharetra. Vestibulum vel mauris et odio lobortis laoreet eget eu magna. Proin mauris erat, luctus at nulla ut, lobortis mattis magna. Morbi a arcu lacus. Maecenas tristique velit vitae nisi consectetur, in mattis diam sodales. Mauris sagittis sem mattis justo bibendum, a eleifend dolor facilisis. Mauris nec pharetra tortor, ac aliquam felis. Nunc pretium erat sed
                            </div>
                        </div>
                        <div class="card-header">
                            <a class="card-title collapsed" data-toggle="collapse" data-parent="#faq" href="#collapse5">
                                Do you offer money back guarantee ?
                            </a>
                        </div>
                        <div id="collapse5" class="card-block collapse">
                            <div class="p-text">
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec luctus tincidunt aliquam. Aliquam gravida massa at sem vulputate interdum et vel eros. Maecenas eros enim, tincidunt vel turpis vel, dapibus tempus nulla. Donec vel nulla dui. Pellentesque sed ante sed ligula hendrerit condimentum. Suspendisse rhoncus fringilla ipsum quis porta. Morbi tincidunt viverra pharetra. Vestibulum vel mauris et odio lobortis laoreet eget eu magna. Proin mauris erat, luctus at nulla ut, lobortis mattis magna. Morbi a arcu lacus. Maecenas tristique velit vitae nisi consectetur, in mattis diam sodales. Mauris sagittis sem mattis justo bibendum, a eleifend dolor facilisis. Mauris nec pharetra tortor, ac aliquam felis. Nunc pretium erat sed
                            </div>
                        </div>
                        <div class="card-header bd-none">
                            <a class="card-title collapsed" data-toggle="collapse" data-parent="#faq" href="#collapse6">
                                What are the restrictions related to payment ?
                            </a>
                        </div>
                        <div id="collapse6" class="card-block collapse">
                            <div class="p-text">
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec luctus tincidunt aliquam. Aliquam gravida massa at sem vulputate interdum et vel eros. Maecenas eros enim, tincidunt vel turpis vel, dapibus tempus nulla. Donec vel nulla dui. Pellentesque sed ante sed ligula hendrerit condimentum. Suspendisse rhoncus fringilla ipsum quis porta. Morbi tincidunt viverra pharetra. Vestibulum vel mauris et odio lobortis laoreet eget eu magna. Proin mauris erat, luctus at nulla ut, lobortis mattis magna. Morbi a arcu lacus. Maecenas tristique velit vitae nisi consectetur, in mattis diam sodales. Mauris sagittis sem mattis justo bibendum, a eleifend dolor facilisis. Mauris nec pharetra tortor, ac aliquam felis. Nunc pretium erat sed
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Faq end -->

{% endblock %}

templates/footer.html
<!-- Footer start -->
<footer class="footer">
    <div class="container footer-inner">
        <div class="row">
            <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6">
                <div class="footer-item clearfix">
                    <img src="img/logos/logo.png" alt="logo" class="f-logo">
                    <div class="text">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas in pulvinar neque. Nulla finibus lobortis pulvinar. Donec a consectetur nulla. Nulla posuere sapien vitae.</p>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
                <div class="footer-item">
                    <h4>Contact Us</h4>
                    <div class="f-border"></div>
                    <ul class="contact-info">
                        <li>
                            <i class="flaticon-pin"></i>Address is here 
                        </li>
                        <li>
                            <i class="flaticon-mail"></i><a href="mailto:sales@hotelempire.com">ubaidparvez4@gmail.com</a>
                        </li>
                        <li>
                            <i class="flaticon-phone"></i><a href="tel:+55-417-634-7071">+91 6005564657</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-xl-2 col-lg-2 col-md-6 col-sm-6">
                <div class="footer-item">
                    <h4>
                        Useful Links
                    </h4>
                    <div class="f-border"></div>
                    <ul class="links">
                        <li>
                            <a href="{% url 'index' %}">Home</a>
                        </li>
                        <li>
                            <a href="{% url 'about' %}">About Us</a>
                        </li>
                        <li>
                            <a href="{% url 'property:list' %}">Property</a>
                        </li>
                        <li>
                            <a href="{% url 'profile_details:signup' %}">Sign up</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer end -->

<!-- Sub footer start -->
<div class="sub-footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-8">
                <p class="copy">© 2019 <a href="#"></a> Designed and developed by Ubaid Parvaiz</p>
            </div>
            <div class="col-lg-4 col-md-4">
                <ul class="social-list clearfix">
                    <li><a href="#" class="facebook"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#" class="twitter"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#" class="google"><i class="fa fa-google-plus"></i></a></li>
                    <li><a href="#" class="rss"><i class="fa fa-rss"></i></a></li>
                    <li><a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- Sub footer end -->

<div id="full-page-search">
    <button type="button" class="close">×</button>
    <form action="http://themevessel-item.s3-website-us-east-1.amazonaws.com/neer/index.html#">
        <input type="search" value="" placeholder="type keyword(s) here" />
        <button type="submit" class="btn btn-sm button-theme">Search</button>
    </form>
</div>

templates/header.html
{% load static %}
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PTNPV7L"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<div class="page_loader"></div>

<!-- Main header start -->
<header class="main-header header-transparent sticky-header">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand logo text-grey" href="index-2.html">
                 <ul class="navbar-nav ml-auto">
                    <li class="nav-item" style="list-style: none;"><a href="" class="nav-link ">logo</a></li>
                 </ul>        
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <ul class="navbar-nav ml-auto">
        
                    <li class="nav-item"><a class="nav-link"   href="{% url 'index' %}">Index</a></li>

                     <li class="nav-item"><a class="nav-link"   href="{% url 'about' %}">About</a></li>

                    <li class="nav-item"><a class="nav-link"   href="{% url 'property:list' %}">Properties</a></li>

                    <li class="nav-item"><a class="nav-link"   href="{% url 'profile_details:signup' %}">Signup</a></li>
                 
            </div>
        </nav>
    </div>
</header>

templates/index.html
{% extends 'base.html' %}
{% block content %}
{% include 'header.html' %}
{% load static %}

<!-- Banner start -->
<div class="banner" id="banner">
    <div id="bannerCarousole" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item banner-max-height active">
                <img class="d-block w-100" src="{% static 'properties/img/banner/banner-2.jpg' %}" alt="banner">
                <div class="carousel-caption banner-slider-inner d-flex h-100 text-center">
                    <div class="carousel-content container">
                        <div class="text-center">
                            <h3 class="text-uppercase">Find Your Property</h3>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                            </p>

                          {% include 'search.html' %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item banner-max-height">
                <img class="d-block w-100" src="{% static 'properties/img/banner/banner-3.jpg' %}" alt="banner">
                <div class="carousel-caption banner-slider-inner d-flex h-100 text-center">
                    <div class="carousel-content container">
                        <div class="text-center">
                            <h3 class="text-uppercase">Find Your Property</h3>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                            </p>
                            {% include 'search.html' %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item banner-max-height">
                <img class="d-block w-100" src="{% static 'properties/img/banner/banner-1.jpg' %}" alt="banner">
                <div class="carousel-caption banner-slider-inner d-flex h-100 text-center">
                    <div class="carousel-content container">
                        <div class="text-center">
                            <h3 class="text-uppercase">Find Your Property</h3>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                            </p>
                          {% include 'search.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#bannerCarousole" role="button" data-slide="prev">
            <span class="slider-mover-left" aria-hidden="true">
                <i class="fa fa-angle-left"></i>
            </span>
        </a>
        <a class="carousel-control-next" href="#bannerCarousole" role="button" data-slide="next">
            <span class="slider-mover-right" aria-hidden="true">
                <i class="fa fa-angle-right"></i>
            </span>
        </a>
    </div>
    <div class="container search-options-btn-area">
        <a class="search-options-btn d-lg-none d-xl-none">
            <div class="search-options d-none d-xl-block d-lg-block">Search Options</div>
            <div class="icon"><i class="fa fa-chevron-up"></i></div>
        </a>
    </div>
</div>
<!-- Banner end -->



<!-- Featured Properties start -->
<div class="featured-properties content-area">
    <div class="container">
        <!-- Main title -->
        <div class="main-title">
            <h1>Featured Properties</h1>
            <p>Find your properties in your city</p>
        </div>
        <!-- Slick slider area start -->
        <div class="slick-slider-area">
            <div class="row slick-carousel" data-slick='{"slidesToShow": 3, "responsive":[{"breakpoint": 1024,"settings":{"slidesToShow": 2}}, {"breakpoint": 768,"settings":{"slidesToShow": 1}}]}'>
                {%  for i in most_recent %}
                <div class="slick-slide-item">
                    <div class="property-box">
                        <div class="property-thumbnail">
                            <a href="{% url 'property:detail' i.pk %}" class="property-img">
                                <div class="listing-badges">
                                    <span class="featured">Featured</span>
                                </div>
                                <div class="price-box"><span>${{i.price}}</span> Per month</div>
                                <img class="d-block w-100" src="{{i.images.url}}"  height = "200px" alt="properties">
                            </a>
                        </div>
                        <div class="detail">
                            <h1 class="title">
                                <a href="{% url 'property:detail' i.pk %}">{{i.title}}</a>
                            </h1>

                            <div class="location">
                                <a href="{% url 'property:detail' i.pk %}">
                                    <i class="flaticon-pin"></i>{{i.address}}
                                </a>
                            </div>
                        </div>
                        <ul class="facilities-list clearfix">
                            <li>
                                <span>Area</span>{{i.area}} Sqft
                            </li>
                            <li>
                                <span>Beds</span> {{i.rooms}}
                            </li>
                            <li>
                                <span>Baths</span> {{i.bathrooms}}
                            </li>
                        </ul>
                        <div class="footer">
                            <a href="#">
                                <i class="flaticon-people"></i> {{i.dealer_name}}
                            </a>
                            <span>
                                <i class="flaticon-calendar"></i>{{i.timestamp | timesince}} ago
                            </span>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="slick-prev slick-arrow-buton">
                <i class="fa fa-angle-left"></i>
            </div>
            <div class="slick-next slick-arrow-buton">
                <i class="fa fa-angle-right"></i>
            </div>
        </div>
    </div>
</div>
<!-- Featured Properties end -->


{% endblock %}

templates/search.html
  <form method="get"  action="{% url 'property:search' %}" >

                                <div class="inline-search-area ml-auto mr-auto d-none d-xl-block d-lg-block">
                                    <div class="row">
                                        <div class="col-xl-2 col-lg-2 col-sm-4 col-6 search-col">
                                            <select class="selectpicker search-fields" name="q1">
                                                <option disabled>Status</option>
                                                <option>For Rent</option>
                                                <option>For Sale</option>
                                            </select>
                                        </div>
                                        <div class="col-xl-2 col-lg-2 col-sm-4 col-6 search-col">
                                            <select class="selectpicker search-fields" name="q3">
                                             <option disabled>Rooms</option>
                                             <option>1</option>
                                             <option>2</option>
                                             <option>3</option>
                                             <option>4</option>
                                             <option>More</option>
                                         </select>
                                     </div>
                                     <div class="col-xl-2 col-lg-2 col-sm-4 col-6 search-col">
                                        <select class="selectpicker search-fields" name="q4">
                                            <option disabled>Bathrooms</option>
                                            <option>1</option>
                                            <option>2</option>
                                            <option>3</option>
                                            <option>4</option>
                                        </select>
                                    </div>
                                    <div class="col-xl-2 col-lg-2 col-sm-4 col-6 search-col">
                                        <select class="selectpicker search-fields" name="q2">
                                         <option disabled>location</option>
                                         <option>California</option>
                                         <option>New york</option>
                                         <option>Chicago</option>
                                     </select>
                                 </div>
                                 <div class="col-xl-2 col-lg-2 col-sm-4 col-6 search-col">
                                    <button class="btn button-theme btn-search btn-block">
                                        <i class="fa fa-search"></i><strong>Find</strong>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>

templates/success.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'header.html' %}

<div class="container py-3">
	<h3>Your message will answered as soon as possible :) </h3>
</div>


{% endblock %}